# Assignment: Writing a Compose File

# version: "2"
version: "3.1"

services:
    
  drupal:
    # image: custom-drupal
    image: drupal:8.2
    # build: .
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres
    environment: 
      # POSTGRES_PASSWORD: example
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
      POSTGRES_USER_FILE: /run/secrets/psql-user
    secrets:
      - psql-user
      - psql-pw
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-modules: 
  drupal-profiles: 
  drupal-themes: 
  drupal-sites: 
    
  drupal-data:


secrets:
  psql-user:
    external: true
  psql-pw:
    external: true