- name: instalar vstfpd
  # hosts: smbprod_trelew
  hosts: ldap-test
  vars:
    usuario: "impresora"
    home_path: "/produccion/shares/{{usuario}}"
  tasks:

    # - name: instalar authorized_key
    #   authorized_key:
    #     user: root
    #     key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYpxCTDRDlajSGnWGbllJI25MrRMk8rIt2n6V6EL1SwkHnS4Fac8r+vEIQuwFFbRvkdlnHW0TLbQkfcD7r082vzDkIr6DqpviN8aSLL/5VHMbXU+KdyA2S3UhrxZVU6FELbUnSepdEsL97n///RqA4MWeF4N77YYMr3eUjtdxq0YfAtGeyBwoumLDMahXV0y8OAoaEpDcw9dhTqJaJ+FVkPuXIVDPRcPuVvFXnHAjiTGP4OMb9iekPwt/gCSbg0hMzqV+HNlCaVYqJs9ZLrcir9HVsZEs2mgfvsbQefkgDBOXXwbr7S2z/4ceYTvTvS79vIDAH5j74s3XWiGG5P8eh root@localhost.localdomain"
    #     # state: absent

    # - name: instalar vstfpd
    #   yum: name=vsftpd state=latest

    # Crear usuario impresora en ldap_trelew y rawson con home en /produccion/shares/impresoras
    - name: siguiente uid libre
      shell: 'echo $( expr $(ldapsearch -H ldap://{{ansible_fqdn}} -x -b \
             "dc=ldap-server,dc=issys,dc=gov,dc=ar" "(objectclass=posixAccount)" uidNumber \
             | grep uidNumber\: \
             | cut -d  " " -f2 \
             | sort -nu \
             | tail -n1) + 1)'
      register: uidNumber

    - debug: var=uidNumber.stdout_lines


    - name: inserto usuario ldap
      ldap_entry:
        bind_dn: cn=Manager,dc=ldap-server,dc=issys,dc=gov,dc=ar
        bind_pw: qwerty
        dn: uid="{{ usuario }}",ou={{usuarios_aplicaciones}},ou={{delegacion}},dc=ldap-server,dc=issys,dc=gov,dc=ar
        objectClass: 
          - top
          - person
          - organizationalPerson
          - inetOrgPerson
          - posixAccount
          - postfixUser
          - shadowAccount
          - sambaSamAccount
        attributes:
          cn: "{{ usuario }}"
          sn: "{{ usuario }}"
          uid: "{{ usuario }}"
          uidNumber: "{{ uidNumber.stdout_lines }}"
          gidNumber: 509
          displayName: "{{ usuario }}"
          givenName: "{{ usuario }}"
          gecos: "{{ usuario }},,,,"
          homeDirectory: "{{home_path}}"
          loginShell: /bin/bash
          mail: null
          mailDomain: null
          mailHomeDir: null
          telephoneNumber: 0
          sambaSID: S-1-5-21-2797552002-818222531-1877314704-513
          sambaAcctFlags: [U]
          sambaKickoffTime: 2147483647
          sambaLMPassword: 19FE4717A7C8B55DAAD3B435B51404EE
          sambaLogoffTime: 2147483647
          sambaLogonTime: 0
          sambaNTPassword: F2C0C177DE720154D024A26E09F0FEB3
          sambaPwdCanChange: 0
          sambaPwdLastSet: 1456146003
          sambaPwdMustChange: 1460034003
          shadowLastChange: -1
          shadowMax: -1
          userPassword: 'e1NTSEF9d3FiVjJMem1XalNZU3dXemgzS29SSk11cU9zdlZHaHU='
        params: "{{ldap_auth}}"

    # - name: borro usuario
    #   ldap_entry:
    #     bind_dn: cn=Manager,dc=ldap-server,dc=issys,dc=gov,dc=ar
    #     bind_pw: qwerty
    #     dn: uid={{usuario}},ou=usuarios,ou={{delegacion}},dc=ldap-server,dc=issys,dc=gov,dc=ar
    #     state: absent
    #     params: "{{ldap_auth}}"


    # - name: copiar archivos de conf
    #   user:
    #     name: impresoras
    #     shell: /bin/bash

    # - name: habilitar servicio ftp y levantar

    # - name: regla iptables para habilitar puertos y salvar iptables
      
      


    # Ejecutar sss_cache -u

    # - name: limpiar cache del sssd - usuario
    #   shell: 'sss_cache -u USUARIO'
    #   args:
    #     executable: /bin/bash



    # - name: limpiar cache del sssd - grupo
    #   shell: 'sss_cache -g GRUPO'
    #   args:
    #     executable: /bin/bash



    # - name: siguiente uid libre
    #   shell: 'echo $( expr $(ldapsearch -H ldap://localhost -x -b \
    #          "dc=ldap-server,dc=issys,dc=gov,dc=ar" "(objectclass=posixAccount)" uidNumber \
    #          | grep uidNumber\: \
    #          | cut -d  " " -f2 \
    #          | sort -nu \
    #          | tail -n1) + 1)'



    #   register: siguiente_uid_libre
    #   args:
    #     executable: /bin/bash      
    # - debug: msg="{{siguiente_uid_libre}}"



    # - name: inserto usuario ldap
    #   ldap_entry:
    #     bind_dn: cn=Manager,dc=ldap-server,dc=issys,dc=gov,dc=ar
    #     bind_pw: qwerty
    #     dn: uid=banana,ou=usuarios,ou=rawson,dc=ldap-server,dc=issys,dc=gov,dc=ar
    #     objectClass: 
    #       - top
    #       - person
    #       - organizationalPerson
    #       - inetOrgPerson
    #       - posixAccount
    #       - postfixUser
    #       - shadowAccount
    #       - sambaSamAccount
    #     attributes:
    #       cn: Banana Pi
    #       sn: Banana Pi
    #       uid: banana
    #       uidNumber: 59595
    #       gidNumber: 509
    #       displayName: Banana Pi
    #       givenName: Banana Pi
    #       gecos: Banana Pi,,,,
    #       homeDirectory: /home/users/banana
    #       loginShell: /bin/bash
    #       mail: banana@issys.gov.ar
    #       mailDomain: banana@issys.gob.ar
    #       mailHomeDir: /produccion/usuarios/banana
    #       telephoneNumber: 0
    #       sambaSID: S-1-5-21-2797552002-818222531-1877314704-513
    #       sambaAcctFlags: [U]
    #       sambaKickoffTime: 2147483647
    #       sambaLMPassword: 19FE4717A7C8B55DAAD3B435B51404EE
    #       sambaLogoffTime: 2147483647
    #       sambaLogonTime: 0
    #       sambaNTPassword: F2C0C177DE720154D024A26E09F0FEB3
    #       sambaPwdCanChange: 0
    #       sambaPwdLastSet: 1456146003
    #       sambaPwdMustChange: 1460034003
    #       shadowLastChange: -1
    #       shadowMax: -1
    #       userPassword: 'e1NTSEF9d3FiVjJMem1XalNZU3dXemgzS29SSk11cU9zdlZHaHU='



    # - name: Set a password for the admin user
    #   ldap_passwd:
    #     bind_dn: cn=Manager,dc=ldap-server,dc=issys,dc=gov,dc=ar
    #     bind_pw: qwerty
    #     dn: "uid=banana,ou=usuarios,ou=rawson,dc=ldap-server,dc=issys,dc=gov,dc=ar"
    #     passwd: "1234"