apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  type: ClusterIP # default
  ports:
    - targetPort: 80    # puerto del back-end
      port: 80          # puerto del service

    selector:
      app: myapp
      type: back-end