# conecta aplicaciones con otras apps o usuarios
Services son objectos (como RS,pods, etc) 

# Casos de Uso:
# -------------  
NodePortService: escuchar un servicio en el NODO y forwardear
la conexion a un POD en un puerto

ClusterIP(default): el servicio crea una IP virtual en el cluster para habilitar
la comunicacion entre diferentes servicios (front-end con back-end services)
Solo se puede acceder desde dentro del cluster. Ej, de pod a pod del cluster (entiendo)

LoadBalancer: load balancer para el servicio soportado en cloud

# NodePort

NODE{30008----[service]--80---80--(10.244.0.2)[POD]}

targetPort: es el 80 del POD donde esta corriendo la app
port: es el 80 del servicio. El seervice tiene su propia ip
NodePort: es el 30008. Es el que accedo desde afuera. Por defecto >30000

service-definition.yml

No puede tener labels
selector: me permite vincular el service con el pod
los labels tal cual del yml del pod
    app: myapp
    type: front-end

kubectl create -f service-definition.yml

# Cuando los pods esstan en un mismo nodo
cuando tengo pods identicos con mismos labels, el service busca por labels, entonces
todos los que matchean los usa como endpoints para requests del usuario. Automatico: Usa Random para
distribuir los pods

# Cuando los pods estan en distintos nodos
el servicio se expande a todos los nodos y abre el mismo puerto en cada nodo



# Comandos kubectl
# -----------------

--dry-run: no crea el recurso y cuenta si el recurso puede ser 
           creado y si el comando esta ok
-o yaml: crea el yaml 


 - POD

# nginx POD
kubectl run --generator=run-pod/vi nginx --image=nginx
kubectl run --generator=run-pod/vi nginx --image=nginx --dry-run -o yaml

# Deployment
kubectl create deployment --image=nginx nginx
kubectl create deployment --image=nginx nginx --dry-run -o yaml


# kubectl create deployment does not have a --replicas option. 
# You could first create it and then scale it using the kubectl scale command.

- SERVICE

# crear un servicio: redis-service ClusterIp para exponer el pod redis en 6378
kubectl expose pod redis --port=6379 --name=redis-service --dry-run -o yaml

# Este no usa pods labels como selectores, asume selectores como app=redis
kubectl create service clusterip redis --tcp=6379:6379 --dry-run -o yaml

