- name: copiar un archivo
  copy: src=borrame2.txt dest=/tmp/  #Directamente busca en files
  notify: notificar

- name: copiar template
  template: src=index.html.j2 dest=/tmp/  #Directamente busca en templates
