apiVersion: v1
kind: Namespace
metadata:
  name: wordns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordns
  name: mi-wordpress
  labels:
    app: wordp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-wordpress
  template:
    metadata:
      name: pod-wordpress
      labels:
        app: pod-wordpress
    spec:
      containers:
      - name: img-wordpress
        image: wordpress:php7.1-apache
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  namespace: wordns
  name: wp-svc
spec:
  # Los pods que aplican a este svc
  selector:
    app: pod-wordpress
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000

