- hosts: centos_minimal
# - hosts: repo
  gather_facts: false
  vars:
    - interfaces: [eth0, eth1, eth2]
    
  tasks:
    # - name: print interfaces
    #   debug:
    #     msg: "{{ interfaces | join('|') }}"

    # - name: A mayusculas
    #   debug:
    #     msg: "{{ ansible_interfaces | map('upper') | list }}"
    
    # - name: Concateno listas
    #   debug:
    #     msg: "{{ ansible_interfaces + [\"VETH-1\", \"VETH-2\"] }}"

    # - name: sleep
    #   shell: "ifdown eth0 down && wall pre sleep && sleep 1 && wall post sleep && ifup eth0 192.168.0.24 up && wall post up"
    #   become: true
    #   async: 1
    #   poll: 0

    # - name: nueva_ip
    #   local_action:
    #     module: set_fact
    #     ansible_host: 192.168.0.24
    #     ansible_user: root
    #     ansible_password: qwerty
    #   delegate_to: localhost


    # - name: Wait for system to become reachable
    #   wait_for_connection:

    # - name: Gather facts for first time
    #   setup:
    
    # - name: test include_vars 23
    #   include_vars: 
    #     file: mis_variables.yml

    - name: test include_vars 
      debug: 
        msg: "{{ mi_variable }}"

